language: java
jdk: oraclejdk8
os: linux
dist: trusty
before_install:
  - chmod +x gradlew
script:
  - "./gradlew build"
before_deploy:
  - git config --local user.name "Redstoneguy129"
  - git config --local user.email "public@cameronwhyte.me"
deploy:
  provider: script
  script: ./gradlew curseforge
  on:
    tags: true
    repo: Redstoneguy129/Metamorphosis
    branch: 1.15.x-production
  skip_cleanup: 'true'
