name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Hey, please remember to be informative with your issues, this way we know how and what to fix. You could even fix the issue yourself by making a PR!'
        pr-message: 'Hey, well done on getting started with your first PR. Remember to follow the steps: https://github.com/Redstoneguy129/Metamorphosis#contribute-to-metamorphosis'
